name: Build PSP Papers Mod Installer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Download dependencies
        run: nuget restore psp-papers-installer/psp-papers-installer.csproj
        env:
          Configuration: ${{ matrix.configuration }}

      - name: Create installer executable
        run: msbuild psp-papers-installer/psp-papers-installer.csproj /p:Configuration=$env:Configuration
        env:
          Configuration: ${{ matrix.configuration }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: PspPapersModInstaller
          path: psp-papers-installer\bin\Release
