name: Build PSP Papers Mod Installer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build installer executable
        run: |
          choco install netfx-4.8.1-devpack -y
          dotnet restore "psp-papers-mod.sln"
          cd .\psp-papers-installer\
          ls
          dotnet msbuild "psp-papers-installer.csproj" /p:Configuration=$env:Configuration
        env:
          Configuration: ${{ matrix.configuration }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: PspPapersModInstaller
          path: .\psp-papers-installer\bin\Release
